version: '3.7'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    restart: on-failure
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BOOTSTRAP_SERVERS: localhost:29092
      KAFKA_TOPIC_TEST: my_topic
      KAFKA_API_VERSION: 7.5.2
      KAFKA_CONSUMER_GROUP: my-test-group
    restart: on-failure
  #producer:
   # build: producer
   # depends_on:
   #     - kafka
   # volumes:
   #   - ./producer:/C:/Users/yanko/OneDrive/Изображения/Документы/Study/ВШЭ/apacheKafkaLab/producer

  #consumer1:
  #  build: consumer
  #  depends_on:
    #    - kafka
   # volumes:
  #    - ./consumer:/C:/Users/yanko/OneDrive/Изображения/Документы/Study/ВШЭ/apacheKafkaLab/consumer
